// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN5XTRXxxu0eFGym0vpNx97Kba7SQWpdk',
    appId: '1:174427428250:web:ce5f02f2cf7f7edad0d623',
    messagingSenderId: '174427428250',
    projectId: 'medal-a571f',
    authDomain: 'medal-a571f.firebaseapp.com',
    storageBucket: 'medal-a571f.firebasestorage.app',
    measurementId: 'G-M3K293G6KN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX2Mcahag09xqKOaj1P1pR4sY2KyWMftQ',
    appId: '1:174427428250:android:0585ada067ee30ced0d623',
    messagingSenderId: '174427428250',
    projectId: 'medal-a571f',
    storageBucket: 'medal-a571f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtM3jigz44KDKfmcfa7FNQOp7cwf2C1GM',
    appId: '1:174427428250:ios:865f9527681144aad0d623',
    messagingSenderId: '174427428250',
    projectId: 'medal-a571f',
    storageBucket: 'medal-a571f.firebasestorage.app',
    iosBundleId: 'com.example.medal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtM3jigz44KDKfmcfa7FNQOp7cwf2C1GM',
    appId: '1:174427428250:ios:865f9527681144aad0d623',
    messagingSenderId: '174427428250',
    projectId: 'medal-a571f',
    storageBucket: 'medal-a571f.firebasestorage.app',
    iosBundleId: 'com.example.medal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAN5XTRXxxu0eFGym0vpNx97Kba7SQWpdk',
    appId: '1:174427428250:web:9896b53abbfede59d0d623',
    messagingSenderId: '174427428250',
    projectId: 'medal-a571f',
    authDomain: 'medal-a571f.firebaseapp.com',
    storageBucket: 'medal-a571f.firebasestorage.app',
    measurementId: 'G-QV51BB5P07',
  );
}
